userId: John Doe <john.doe@example.com>
folderPathGenerated: F:\pgp\input
folderPathEncrypted: F:\pgp\encrypted
folderPathDecrypted: F:\pgp\decrypted
publicKey: F:\pgp\public.asc
privateKey: F:\pgp\private.asc
password: myPassphrase